### ISSUE TITLE
Crash on placing rocket

### ISSUE THREAD

**Issue by PureTryOut** [TeamGalacticraft/Galacticraft#363]
### Version Information

4ec4a1fb6f011ff81a4a29a142d12479b7cbc399

### Log or Crash Report

```
[15:42:27] [Netty Server IO #7/ERROR]: Error sending packet clientbound/minecraft:custom_payload
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (galacticraft:spawn_rocket)
	at net.minecraft.class_9136.handler$zke000$fabric-networking-api-v1$encode(class_9136.java:547) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.class_9139$11.encode(class_9139.java:136) ~[client-intermediary.jar:?]
	at dev.galacticraft.mod.util.StreamCodecs$1.encode(StreamCodecs.java:101) ~[Galacticraft-5.0.0-prealpha+288.jar:?]
	at dev.galacticraft.mod.util.StreamCodecs$3.encode(StreamCodecs.java:163) ~[Galacticraft-5.0.0-prealpha+288.jar:?]
	at net.minecraft.class_8710$1.method_56489(class_8710.java:52) ~[client-intermediary.jar:?]
	at net.minecraft.class_8710$1.method_56490(class_8710.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_8710$1.encode(class_8710.java:39) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[client-intermediary.jar:?]
	... 33 more
[15:42:27] [Netty Server IO #7/ERROR]: Error sending packet clientbound/minecraft:set_entity_data
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:set_entity_data'
	at net.minecraft.class_9136.method_56426(class_9136.java:55) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[client-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.writePromiseCombiner(MessageToMessageEncoder.java:140) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:120) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[client-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[client-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.class_9139$11.encode(class_9139.java:136) ~[client-intermediary.jar:?]
	at dev.galacticraft.mod.util.StreamCodecs$1.encode(StreamCodecs.java:101) ~[Galacticraft-5.0.0-prealpha+288.jar:?]
	at net.minecraft.class_2945$class_7834.method_46361(class_2945.java:144) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_46615(class_2739.java:26) ~[client-intermediary.jar:?]
	at net.minecraft.class_2739.method_55926(class_2739.java:44) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$6.encode(class_9139.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[client-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[client-intermediary.jar:?]
	... 33 more
[15:42:27] [Server thread/INFO]: PureTryOut lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:custom_payload' (galacticraft:spawn_rocket)
```

### Reproduction steps

1. Spawn a rocket (normal or the creative one)
2. Place it on a launch pad
3. ???
4. Crash

**Comment by Roelymole** [comment]
I am guessing by spawn a rocket you mean put a rocket into your inventory from the creative menu.

I can't reproduce this myself, could you confirm if it still happens for you?

**Comment by PureTryOut** [comment]
I can not reproduce this any more either, but then again it's been 4 months since I reported this 😛  Thanks!

Now to figure out again how to fuel the the thing and fly in it, it's been a while...
